server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.6.129
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.6.129
ly: #自定义短信
  sms:
    accessKeyId: xx # 你自己的accessKeyId
    accessKeySecret: xx # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_183760648 # 模板名称